services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $apiSecretKey: '%sfs_customer.adapter.stripe.apiSecretKey%'
            $webhookSigningSecret: '%sfs_customer.adapter.stripe.webhookSigningSecret%'
            $logger: '@?monolog.logger.stripe'

    Softspring\CustomerBundle\Platform\Adapter\CustomerAdapterInterface:
        class: Softspring\CustomerBundle\Platform\Adapter\Stripe\CustomerAdapter
        tags:
            - { name: 'sfs_customer.platform.adapter', alias: 'customer' }

    Softspring\CustomerBundle\Platform\Adapter\SourceAdapterInterface:
        class: Softspring\CustomerBundle\Platform\Adapter\Stripe\SourceAdapter
        tags:
          - { name: 'sfs_customer.platform.adapter', alias: 'source' }

    Softspring\CustomerBundle\Platform\Adapter\AddressAdapterInterface:
        class: Softspring\CustomerBundle\Platform\Adapter\Stripe\AddressAdapter
        tags:
          - { name: 'sfs_customer.platform.adapter', alias: 'address' }

    Softspring\CustomerBundle\Platform\Adapter\NotifyAdapterInterface:
        class: Softspring\CustomerBundle\Platform\Adapter\Stripe\NotifyAdapter
        tags:
            - { name: 'sfs_customer.platform.adapter', alias: 'notify' }

    Softspring\CustomerBundle\Doctrine\EntityListener\StripeAddressEntityListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', method: 'preUpdate', entity: '%sfs_customer.address.class%' } # , entity_manager: '%sfs_customer.entity_manager_name%' }
            - { name: 'doctrine.orm.entity_listener', event: 'prePersist', method: 'prePersist', entity: '%sfs_customer.address.class%' } # , entity_manager: '%sfs_customer.entity_manager_name%' }
            - { name: 'doctrine.orm.entity_listener', event: 'preRemove', method: 'preRemove', entity: '%sfs_customer.address.class%' } # , entity_manager: '%sfs_customer.entity_manager_name%' }

    Softspring\CustomerBundle\Doctrine\EntityListener\StripeCustomerEntityListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', method: 'preUpdate', entity: '%sfs_customer.customer.class%' } # , entity_manager: '%sfs_customer.entity_manager_name%' }
            - { name: 'doctrine.orm.entity_listener', event: 'prePersist', method: 'prePersist', entity: '%sfs_customer.customer.class%' } # , entity_manager: '%sfs_customer.entity_manager_name%' }
            - { name: 'doctrine.orm.entity_listener', event: 'preRemove', method: 'preRemove', entity: '%sfs_customer.customer.class%' } # , entity_manager: '%sfs_customer.entity_manager_name%' }

    Softspring\CustomerBundle\Doctrine\EntityListener\StripeSourceEntityListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', method: 'preUpdate', entity: '%sfs_customer.source.class%' } # , entity_manager: '%sfs_customer.entity_manager_name%' }
            - { name: 'doctrine.orm.entity_listener', event: 'prePersist', method: 'prePersist', entity: '%sfs_customer.source.class%' } # , entity_manager: '%sfs_customer.entity_manager_name%' }
            - { name: 'doctrine.orm.entity_listener', event: 'preRemove', method: 'preRemove', entity: '%sfs_customer.source.class%' } # , entity_manager: '%sfs_customer.entity_manager_name%' }
