services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_customer.entity_manager'
            $api: '@Softspring\CustomerBundle\Platform\ApiManagerInterface'

    Softspring\CustomerBundle\Controller\:
        resource: '../../../Controller/*'
        public: true

    Softspring\CustomerBundle\Form\:
        resource: '../../../Form/*'

    Softspring\CustomerBundle\Manager\:
        resource: '../../../Manager/*'

    Softspring\CustomerBundle\Manager\SourceManagerInterface:
        class: Softspring\CustomerBundle\Manager\SourceManager
        arguments:
            $targetClass: 'Softspring\CustomerBundle\Model\SourceInterface'

    Softspring\CustomerBundle\Manager\AddressManagerInterface:
        class: Softspring\CrudlBundle\Manager\DefaultCrudlEntityManager
        arguments:
            $targetClass: 'Softspring\CustomerBundle\Model\AddressInterface'

    Softspring\CustomerBundle\Platform\ApiManagerInterface:
        class: Softspring\CustomerBundle\Platform\ApiManager
        arguments:
            $name: '%sfs_customer.adapter.name%'
            $adapters: []