security:
    role_hierarchy:
        ROLE_CUSTOMERS_ADMIN_CUSTOMERS:
            - ROLE_CUSTOMERS_ADMIN_CUSTOMERS_LIST
            - ROLE_CUSTOMERS_ADMIN_CUSTOMERS_DETAILS
            - ROLE_CUSTOMERS_ADMIN_CUSTOMERS_CREATE